{{ if .Values.sealedsecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.cluster.name }}-sealed-secrets
  labels:
    cluster: {{ .Values.cluster.name | quote }}
    app: sealed-secrets
  namespace: argocd
  annotations:
    {{- toYaml .Values.notifications | nindent 4 }}
spec:
  project: {{ .Values.cluster.name }}
  destination:
    server: {{ .Values.cluster.url }}
    namespace: kube-system
  syncPolicy:
    {{- if .Values.sync }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    chart: sealed-secrets
    targetRevision: {{ .Values.sealedsecrets.version | quote }}
    helm:
      version: v3
      releaseName: sealed-secrets-controller
{{- end }}
